NAUTILUS_SCRIPTS_DIR=~/.gnome2/nautilus-scripts

install: uninstall 
	mkdir -p $(NAUTILUS_SCRIPTS_DIR)/.rdata
	cp -Rfv po  $(NAUTILUS_SCRIPTS_DIR)/.rdata/
	cp -Rfv icon $(NAUTILUS_SCRIPTS_DIR)/.rdata/

	cp -fv nautilus-renamer.py $(NAUTILUS_SCRIPTS_DIR)/Renamer

uninstall:
	rm -rf $(NAUTILUS_SCRIPTS_DIR)/.rdata
	rm -rf $(NAUTILUS_SCRIPTS_DIR)/Renamer

.PHONY: all clean install
