#!/usr/bin/env python

import os;
import sys;
import shutil;

top_dir = os.getcwd ()
sys.path.append (os.path.join (top_dir, 'scripts'))

try:
    import genmo
except:
    print "Unable to import genmo ..."
    sys.exit (1)
    
NAUTILUS_SCRIPTS_LOCAL_DIR = os.path.expanduser('~/.gnome2/nautilus-scripts')
NAUTILUS_SCRIPTS_GLOBAL_DIR = os.path.join (sys.prefix, 'share', 'nautilus-scripts')
LOCALE_DIR = os.path.join (sys.prefix, 'share', 'locale')

genmo.gen_mo_files (os.path.join (top_dir, 'po'), LOCALE_DIR)

try:
    script = os.path.join (top_dir, 'nautilus-renamer.py')
    copy_to = os.path.join (NAUTILUS_SCRIPTS_GLOBAL_DIR, 'Renamer')
    link_to = os.path.join (NAUTILUS_SCRIPTS_LOCAL_DIR, 'Renamer')

    os.remove (copy_to)
    os.remove (link_to)
    
    shutil.copy2 (script, copy_to)
    print "Copying %s to %s ..." % (script, copy_to)
    
    os.symlink (copy_to, link_to)
    print "Creating Symlink %s to %s ..." % (script, copy_to) 
except:
    pass 




