#!/usr/bin/env python

import os;
import sys;
import shutil;

top_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append (os.path.join (top_dir, 'scripts'))

try:
    import genmo
except:
    print "Unable to import genmo ..."
    sys.exit (1)
    
NAUTILUS_SCRIPTS_LOCAL_DIR = os.path.expanduser('~/.gnome2/nautilus-scripts')
NAUTILUS_SCRIPTS_GLOBAL_DIR = os.path.join (sys.prefix, 'share', 'nautilus-scripts')
LOCALE_DIR = os.path.join (sys.prefix, 'share', 'locale')

DOC_FILES = ['README', 'COPYING', 'ChangeLog', 'TODO' , 'AUTHORS']

genmo.gen_mo_files (os.path.join (top_dir, 'po'), LOCALE_DIR)

try:
    script = os.path.join (top_dir, 'nautilus-renamer.py')
    copy_to = os.path.join (NAUTILUS_SCRIPTS_GLOBAL_DIR, 'Renamer')
    link_to = os.path.join (NAUTILUS_SCRIPTS_LOCAL_DIR, 'Renamer')

    shutil.copy2 (script, copy_to)
    print "Copying %s to %s ..." % (script, copy_to)

    try:
        os.remove (link_to)
    except:
        pass

    os.symlink (copy_to, link_to)
    print "Creating Symlink %s to %s ..." % (script, copy_to)

    for file in DOC_FILES:
        copy_to = os.path.join (sys.prefix, 'share', 'doc', file)
        shutil.copy2 (os.path.join (top_dir, file), copy_to)
        print "Copying %s to %s ..." % (file, copy_to)
        
except:
    print "Install Failed !!!"
